name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: npm install, build, and test
        working-directory: src/client
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: client
          path: /src/client
  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy
    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v3
        with:
          name: client
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_STONE_0DA6E8F10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/src/client"
          api_location: ""
          output_location: ""
          skip_app_build: true
